// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GoogleConstants
{
        public const string leaderboard_spiral_mode_highscore = "CgkIyOLKsZgIEAIQBw"; // <GPGSID>
        public const string achievement_unlock_neo_lightning = "CgkIyOLKsZgIEAIQEA"; // <GPGSID>
        public const string achievement_play_10_games = "CgkIyOLKsZgIEAIQFA"; // <GPGSID>
        public const string achievement_unlock_admiral = "CgkIyOLKsZgIEAIQEQ"; // <GPGSID>
        public const string leaderboard_slalom_mode_highscore = "CgkIyOLKsZgIEAIQCA"; // <GPGSID>
        public const string achievement_unlock_type_x = "CgkIyOLKsZgIEAIQEg"; // <GPGSID>
        public const string achievement_spiral_mode_master = "CgkIyOLKsZgIEAIQGw"; // <GPGSID>
        public const string achievement_play_100_games = "CgkIyOLKsZgIEAIQFg"; // <GPGSID>
        public const string achievement_unlock_maester_iv = "CgkIyOLKsZgIEAIQDg"; // <GPGSID>
        public const string achievement_play_50_games = "CgkIyOLKsZgIEAIQFQ"; // <GPGSID>
        public const string achievement_unlock_pink_vengeance = "CgkIyOLKsZgIEAIQBA"; // <GPGSID>
        public const string achievement_unlock_spiral_mode = "CgkIyOLKsZgIEAIQAg"; // <GPGSID>
        public const string achievement_unlock_fast_mode = "CgkIyOLKsZgIEAIQAQ"; // <GPGSID>
        public const string achievement_unlock_greenhorn_cruiser = "CgkIyOLKsZgIEAIQAw"; // <GPGSID>
        public const string achievement_normal_mode_master = "CgkIyOLKsZgIEAIQGQ"; // <GPGSID>
        public const string achievement_three_strikes_mode = "CgkIyOLKsZgIEAIQCw"; // <GPGSID>
        public const string achievement_play_500_games = "CgkIyOLKsZgIEAIQFw"; // <GPGSID>
        public const string achievement_unlock_chocomint_fighter = "CgkIyOLKsZgIEAIQDQ"; // <GPGSID>
        public const string leaderboard_normal_mode_highscore = "CgkIyOLKsZgIEAIQBg"; // <GPGSID>
        public const string achievement_hyperspeed_mode_master = "CgkIyOLKsZgIEAIQHQ"; // <GPGSID>
        public const string leaderboard_three_strikes_leaderboard = "CgkIyOLKsZgIEAIQCg"; // <GPGSID>
        public const string achievement_three_strikes_mode_master = "CgkIyOLKsZgIEAIQGg"; // <GPGSID>
        public const string leaderboard_hyperspeed_mode_highscore = "CgkIyOLKsZgIEAIQCQ"; // <GPGSID>
        public const string achievement_spaceship_designer = "CgkIyOLKsZgIEAIQHg"; // <GPGSID>
        public const string achievement_play_5_games = "CgkIyOLKsZgIEAIQEw"; // <GPGSID>
        public const string achievement_slalom_mode_master = "CgkIyOLKsZgIEAIQHA"; // <GPGSID>
        public const string achievement_unlock_radical_bomber = "CgkIyOLKsZgIEAIQDw"; // <GPGSID>
        public const string achievement_play_1000_games = "CgkIyOLKsZgIEAIQGA"; // <GPGSID>
        public const string achievement_unlock_slalom_mode = "CgkIyOLKsZgIEAIQDA"; // <GPGSID>

}

